# docker-compose.yml
services:
  db:
    image: postgres
    restart: always
    volumes:
      - ./app/data/db:/var/lib/postgresql/data
    env_file:
      - .env

  web:
    build: .
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: python manage.py runserver 0.0.0.0:8000

  adminer:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - "8080:8080"
