# Generated by Django 4.0.3 on 2022-03-13 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estancia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_estancia', models.CharField(max_length=5)),
                ('n_zona', models.IntegerField()),
                ('n_sector', models.IntegerField()),
                ('observaciones', models.CharField(max_length=200)),
                ('croquis_plata', models.ImageField(upload_to='')),
                ('n_planta', models.IntegerField()),
                ('n_seccion', models.IntegerField()),
                ('elevacion', models.IntegerField()),
                ('tpq', models.IntegerField()),
                ('taq', models.IntegerField()),
                ('fase', models.CharField(choices=[('A: época contemporánea', (('A1', 'A1'), ('A2', 'A2'), ('A3', 'A3'))), ('B: época moderna', (('B1', 'B1'), ('B2', 'B2'))), ('C: época medieval', (('C1', 'C1'), ('C2', 'C2'), ('C3', 'C3'), ('C4', 'C4'), ('C5', 'C5'))), ('D: época romana', (('D1', 'D1'), ('D2', 'D2'), ('D3', 'D3'), ('D4', 'D4'))), ('E: época ibérica', (('E1', 'E1'), ('E2', 'E2'), ('E3', 'E3'), ('E4', 'E4'))), ('F: Edad del Bronce', (('F1', 'F1'), ('F2', 'F2'), ('F3', 'F3')))], max_length=2)),
                ('periodo', models.CharField(choices=[('Contemporánea: 1800/1900', 'Contemporánea: 1800/1900'), ('Contemporánea: 1900/2000', 'Contemporánea: 1900/2000'), ('Contemporánea: actualidad', 'Contemporánea: actualidad'), ('Moderna: morisca', 'Moderna: morisca'), ('Moderna: cristiana', 'Moderna: cristiana'), ('Medieval: emiral', 'Medieval: emiral'), ('Medieval: califal', 'Medieval: califal'), ('Medieval: taifas', 'Medieval: taifas'), ('Medieval: almorávide/almohade', 'Medieval: almorávide/almohade'), ('Medieval: nazarí', 'Medieval: nazarí'), ('Romana: época republicana', 'Romana: época republicana'), ('Romana: Alto Imperio', 'Romana: Alto Imperio'), ('Romana: Bajo Imperio', 'Romana: Bajo Imperio'), ('Romana: Antigüedad tardía', 'Romana: Antigüedad tardía'), ('Ibérica: Protoibérico', 'Ibérica: Protoibérico'), ('Ibérica: Ibérico antiguo', 'Ibérica: Ibérico antiguo'), ('Ibérica: Ibérico pleno', 'Ibérica: Ibérico pleno'), ('Ibérica: Ibérico tardío o final', 'Ibérica: Ibérico tardío o final'), ('Edad del Bronce: final', 'Edad del Bronce: final'), ('Edad del Bronce: argárico', 'Edad del Bronce: argárico'), ('Edad del Bronce: antiguo', 'Edad del Bronce: antiguo')], max_length=100)),
                ('autor', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Excavacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_excavacion', models.IntegerField(unique=True, verbose_name='Número de excavación')),
                ('punto_cero', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Hecho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letra', models.CharField(choices=[('MR', 'Muro'), ('SL', 'Suelo'), ('PO', 'Pozo'), ('FS', 'Fosa'), ('SI', 'Silo'), ('PR', 'Puerta'), ('CN', 'Canalización'), ('DP', 'Depósito'), ('TN', 'Tinaja'), ('ES', 'Sin identificación')], max_length=2)),
                ('numero', models.CharField(max_length=6)),
                ('fase', models.CharField(choices=[('A: época contemporánea', (('A1', 'A1'), ('A2', 'A2'), ('A3', 'A3'))), ('B: época moderna', (('B1', 'B1'), ('B2', 'B2'))), ('C: época medieval', (('C1', 'C1'), ('C2', 'C2'), ('C3', 'C3'), ('C4', 'C4'), ('C5', 'C5'))), ('D: época romana', (('D1', 'D1'), ('D2', 'D2'), ('D3', 'D3'), ('D4', 'D4'))), ('E: época ibérica', (('E1', 'E1'), ('E2', 'E2'), ('E3', 'E3'), ('E4', 'E4'))), ('F: Edad del Bronce', (('F1', 'F1'), ('F2', 'F2'), ('F3', 'F3')))], max_length=2)),
                ('tpq', models.IntegerField()),
                ('taq', models.IntegerField()),
                ('definicion', models.CharField(max_length=100)),
                ('comentarios', models.CharField(max_length=100)),
                ('sector', models.IntegerField()),
                ('zona', models.IntegerField()),
                ('año', models.IntegerField()),
                ('estructura', models.CharField(max_length=10)),
                ('croquis_plan', models.ImageField(upload_to='')),
                ('croquis_seccion', models.ImageField(upload_to='')),
                ('estancia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myFindings.estancia')),
            ],
        ),
        migrations.CreateModel(
            name='UE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plano_n', models.IntegerField()),
                ('seccion_n', models.IntegerField()),
                ('elevacion_n', models.IntegerField()),
                ('croquis_planta', models.ImageField(upload_to='')),
                ('croquis_seccion', models.ImageField(upload_to='')),
                ('tpq', models.IntegerField()),
                ('taq', models.IntegerField()),
                ('fase', models.CharField(choices=[('A: época contemporánea', (('A1', 'A1'), ('A2', 'A2'), ('A3', 'A3'))), ('B: época moderna', (('B1', 'B1'), ('B2', 'B2'))), ('C: época medieval', (('C1', 'C1'), ('C2', 'C2'), ('C3', 'C3'), ('C4', 'C4'), ('C5', 'C5'))), ('D: época romana', (('D1', 'D1'), ('D2', 'D2'), ('D3', 'D3'), ('D4', 'D4'))), ('E: época ibérica', (('E1', 'E1'), ('E2', 'E2'), ('E3', 'E3'), ('E4', 'E4'))), ('F: Edad del Bronce', (('F1', 'F1'), ('F2', 'F2'), ('F3', 'F3')))], max_length=2)),
                ('periodo', models.CharField(choices=[('Contemporánea: 1800/1900', 'Contemporánea: 1800/1900'), ('Contemporánea: 1900/2000', 'Contemporánea: 1900/2000'), ('Contemporánea: actualidad', 'Contemporánea: actualidad'), ('Moderna: morisca', 'Moderna: morisca'), ('Moderna: cristiana', 'Moderna: cristiana'), ('Medieval: emiral', 'Medieval: emiral'), ('Medieval: califal', 'Medieval: califal'), ('Medieval: taifas', 'Medieval: taifas'), ('Medieval: almorávide/almohade', 'Medieval: almorávide/almohade'), ('Medieval: nazarí', 'Medieval: nazarí'), ('Romana: época republicana', 'Romana: época republicana'), ('Romana: Alto Imperio', 'Romana: Alto Imperio'), ('Romana: Bajo Imperio', 'Romana: Bajo Imperio'), ('Romana: Antigüedad tardía', 'Romana: Antigüedad tardía'), ('Ibérica: Protoibérico', 'Ibérica: Protoibérico'), ('Ibérica: Ibérico antiguo', 'Ibérica: Ibérico antiguo'), ('Ibérica: Ibérico pleno', 'Ibérica: Ibérico pleno'), ('Ibérica: Ibérico tardío o final', 'Ibérica: Ibérico tardío o final'), ('Edad del Bronce: final', 'Edad del Bronce: final'), ('Edad del Bronce: argárico', 'Edad del Bronce: argárico'), ('Edad del Bronce: antiguo', 'Edad del Bronce: antiguo')], max_length=100)),
                ('descripcion', models.CharField(max_length=200)),
                ('autor', models.CharField(max_length=30)),
                ('año', models.IntegerField()),
                ('interpretacion', models.CharField(choices=[('Ocupacion', 'Ocupación'), ('Abandono', 'Abandono'), ('Contruccion', 'Construcción'), ('Paleosuelo', 'Paleosuelo'), ('Reinstalacion', 'Reinstalación'), ('Coluvion', 'Coluvión/Aluvión'), ('Destruccion', 'Destrucción'), ('Relleno', 'Relleno'), ('Otras', 'Otras')], max_length=13)),
                ('sector', models.CharField(max_length=2)),
                ('observaciones', models.CharField(max_length=200)),
                ('coordenadas', models.CharField(max_length=100)),
                ('cota_superior_diff', models.IntegerField()),
                ('cota_inferior_diff', models.IntegerField()),
                ('pendiente_superior', models.CharField(choices=[('Norte', 'Norte'), ('Sur', 'Sur'), ('Este', 'Este'), ('Oeste', 'Oeste'), ('Noroeste', 'Noroeste'), ('Noreste', 'Noreste'), ('Suroeste', 'Suroeste'), ('Sureste', 'Sureste')], max_length=8)),
                ('pendiente_inferior', models.CharField(choices=[('Norte', 'Norte'), ('Sur', 'Sur'), ('Este', 'Este'), ('Oeste', 'Oeste'), ('Noroeste', 'Noroeste'), ('Noreste', 'Noreste'), ('Suroeste', 'Suroeste'), ('Sureste', 'Sureste')], max_length=8)),
                ('excavacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myFindings.excavacion')),
                ('hecho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myFindings.hecho')),
            ],
        ),
        migrations.CreateModel(
            name='UEConstruida',
            fields=[
                ('ue_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='myFindings.ue')),
                ('sistema_constructivo', models.CharField(max_length=50)),
                ('tipo', models.CharField(choices=[('POS', 'Positiva'), ('NEG', 'Negativa')], max_length=3)),
            ],
            bases=('myFindings.ue',),
        ),
        migrations.CreateModel(
            name='UESedimentaria',
            fields=[
                ('ue_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='myFindings.ue')),
                ('tipo_estructura', models.CharField(choices=[('CO', 'Compacta'), ('SU', 'Suelta'), ('HO', 'Homogénea'), ('HE', 'Heterogénea')], max_length=2)),
                ('tipo_textura', models.CharField(choices=[('ARC', 'Arcilla'), ('LIM', 'Limo'), ('ARE', 'Arena'), ('GRA', 'Grava'), ('CAN', 'Cantos'), ('BLO', 'Bloques'), ('CER', 'Cerámica'), ('MOR', 'Mortero')], max_length=3)),
            ],
            bases=('myFindings.ue',),
        ),
        migrations.CreateModel(
            name='Fotografia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(unique=True)),
                ('tipo', models.CharField(max_length=50)),
                ('fase', models.CharField(choices=[('A: época contemporánea', (('A1', 'A1'), ('A2', 'A2'), ('A3', 'A3'))), ('B: época moderna', (('B1', 'B1'), ('B2', 'B2'))), ('C: época medieval', (('C1', 'C1'), ('C2', 'C2'), ('C3', 'C3'), ('C4', 'C4'), ('C5', 'C5'))), ('D: época romana', (('D1', 'D1'), ('D2', 'D2'), ('D3', 'D3'), ('D4', 'D4'))), ('E: época ibérica', (('E1', 'E1'), ('E2', 'E2'), ('E3', 'E3'), ('E4', 'E4'))), ('F: Edad del Bronce', (('F1', 'F1'), ('F2', 'F2'), ('F3', 'F3')))], max_length=2)),
                ('vista_desde', models.CharField(max_length=50)),
                ('dist_focal', models.IntegerField()),
                ('descripcion', models.CharField(max_length=100)),
                ('imagen', models.ImageField(upload_to='')),
                ('estancia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myFindings.estancia')),
                ('ue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myFindings.ue')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialSedimentaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('MUE', 'Muestras'), ('MET', 'Metal'), ('PIE', 'Piedra'), ('ARC', 'Arcilla'), ('MCO', 'Material construido'), ('CER', 'Cerámica'), ('VID', 'Vidrio'), ('FAU', 'Fauna'), ('OTR', 'Otros')], max_length=3)),
                ('uesedimentaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myFindings.uesedimentaria')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialConstruida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('PIE', 'Piedra'), ('TCR', 'Tierra cruda'), ('CAL', 'Cal'), ('TCO', 'Tierra cocida'), ('MAD', 'Madera')], max_length=3)),
                ('ueconstruida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myFindings.ueconstruida')),
            ],
        ),
        migrations.CreateModel(
            name='Inclusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frecuencia', models.IntegerField(choices=[(0, 'Ausencia'), (1, 'Ocasional'), (2, 'Medio'), (3, 'Frecuente')])),
                ('grosor', models.IntegerField(choices=[(1, '< 2 cm'), (2, '2-6 cm'), (3, '6-12 cm'), (4, '> 12 cm')])),
                ('tipo', models.CharField(choices=[('CEN', 'Cenizas'), ('CAR', 'Carbones'), ('HUE', 'Huesos'), ('ADO', 'Adobe'), ('CAÑ', 'Cañizo'), ('TEJ', 'Tejas'), ('BLO', 'Bloques'), ('CAL', 'Cal'), ('MOR', 'Mortero'), ('ENL', 'Enlucido')], max_length=3)),
                ('uesedimentaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myFindings.uesedimentaria')),
            ],
        ),
    ]
