# Generated by Django 4.0.4 on 2022-04-24 14:40

from django.db import migrations

def initialize_built_materials(apps, schema_editor):
    BuiltMaterial = apps.get_model('myFindings', 'BuiltMaterial')
    BuiltMaterial.objects.create(nombre='Piedra')
    BuiltMaterial.objects.create(nombre='Tierra cruda')
    BuiltMaterial.objects.create(nombre='Cal')
    BuiltMaterial.objects.create(nombre='Tierra cocida')
    BuiltMaterial.objects.create(nombre='Madera')
    BuiltMaterial.objects.create(nombre='Otros')
    
def initialize_sedimentary_materials(apps, schema_editor):
    SedimentaryMaterial = apps.get_model('myFindings', 'SedimentaryMaterial')
    SedimentaryMaterial.objects.create(nombre='Muestras')
    SedimentaryMaterial.objects.create(nombre='Metal')
    SedimentaryMaterial.objects.create(nombre='Piedra')
    SedimentaryMaterial.objects.create(nombre='Arcilla')
    SedimentaryMaterial.objects.create(nombre='Material construcción')
    SedimentaryMaterial.objects.create(nombre='Cerámica')
    SedimentaryMaterial.objects.create(nombre='Vidrio')
    SedimentaryMaterial.objects.create(nombre='Fauna')
    SedimentaryMaterial.objects.create(nombre='Otros')

class Migration(migrations.Migration):

    dependencies = [
        ('myFindings', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(initialize_built_materials),
        migrations.RunPython(initialize_sedimentary_materials),
    ]
