# Generated by Django 4.0.4 on 2022-05-12 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myFindings', '0002_auto_20220424_1440'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='builtmaterial',
            options={'verbose_name': 'material construido', 'verbose_name_plural': 'materiales construidos'},
        ),
        migrations.AlterModelOptions(
            name='builtue',
            options={'verbose_name': 'unidad construida', 'verbose_name_plural': 'unidades construidas'},
        ),
        migrations.AlterModelOptions(
            name='excavation',
            options={'verbose_name': 'excavación', 'verbose_name_plural': 'excavaciones'},
        ),
        migrations.AlterModelOptions(
            name='photo',
            options={'verbose_name': 'fotografía', 'verbose_name_plural': 'fotografías'},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'verbose_name': 'estancia', 'verbose_name_plural': 'estancias'},
        ),
        migrations.AlterModelOptions(
            name='sedimentarymaterial',
            options={'verbose_name': 'material sedimentario', 'verbose_name_plural': 'materiales sedimentarios'},
        ),
        migrations.AlterModelOptions(
            name='sedimentaryue',
            options={'verbose_name': 'unidad sedimentaria', 'verbose_name_plural': 'unidades sedimentarias'},
        ),
    ]
