# Generated by Django 4.0.4 on 2022-05-26 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myFindings', '0002_auto_20220424_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='excavation',
            name='nombre',
            field=models.CharField(default='', max_length=100, verbose_name='Nombre de la excavación'),
        ),
    ]
