# Generated by Django 4.0.3 on 2022-03-14 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myFindings', '0002_rename_croquis_plata_estancia_croquis_planta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='excavacion',
            old_name='punto_cero',
            new_name='altura',
        ),
        migrations.RemoveField(
            model_name='inclusion',
            name='id',
        ),
        migrations.RemoveField(
            model_name='materialconstruida',
            name='id',
        ),
        migrations.RemoveField(
            model_name='materialconstruida',
            name='ueconstruida',
        ),
        migrations.RemoveField(
            model_name='materialsedimentaria',
            name='id',
        ),
        migrations.RemoveField(
            model_name='materialsedimentaria',
            name='uesedimentaria',
        ),
        migrations.RemoveField(
            model_name='ue',
            name='coordenadas',
        ),
        migrations.AddField(
            model_name='excavacion',
            name='coordenada_x',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='excavacion',
            name='coordenada_y',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ue',
            name='coordenada_x',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ue',
            name='coordenada_y',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='inclusion',
            name='tipo',
            field=models.CharField(choices=[('CEN', 'Cenizas'), ('CAR', 'Carbones'), ('HUE', 'Huesos'), ('ADO', 'Adobe'), ('CAÑ', 'Cañizo'), ('TEJ', 'Tejas'), ('BLO', 'Bloques'), ('CAL', 'Cal'), ('MOR', 'Mortero'), ('ENL', 'Enlucido')], max_length=3, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='materialconstruida',
            name='nombre',
            field=models.CharField(choices=[('PIE', 'Piedra'), ('TCR', 'Tierra cruda'), ('CAL', 'Cal'), ('TCO', 'Tierra cocida'), ('MAD', 'Madera')], max_length=3, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='materialsedimentaria',
            name='nombre',
            field=models.CharField(choices=[('MUE', 'Muestras'), ('MET', 'Metal'), ('PIE', 'Piedra'), ('ARC', 'Arcilla'), ('MCO', 'Material construido'), ('CER', 'Cerámica'), ('VID', 'Vidrio'), ('FAU', 'Fauna'), ('OTR', 'Otros')], max_length=3, primary_key=True, serialize=False),
        ),
    ]
