# Generated by Django 4.0.5 on 2022-06-06 10:54

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myFindings', '0002_auto_20220424_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fact',
            name='croquis_plan',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Croquis del plan'),
        ),
        migrations.AlterField(
            model_name='fact',
            name='croquis_seccion',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Croquis de la sección'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='imagen',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='room',
            name='croquis_planta',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Croquis de la planta'),
        ),
        migrations.AlterField(
            model_name='ue',
            name='croquis_planta',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Croquis de la planta'),
        ),
        migrations.AlterField(
            model_name='ue',
            name='croquis_seccion',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Croquis de la sección'),
        ),
    ]
