# Generated by Django 4.0.4 on 2022-04-30 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myFindings', '0002_auto_20220424_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ue',
            name='codigo',
            field=models.CharField(blank=True, max_length=6, unique=True),
        ),
    ]
