# Generated by Django 4.0.4 on 2022-05-26 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myFindings', '0003_excavation_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='ue',
            name='bajo',
            field=models.ManyToManyField(blank=True, to='myFindings.ue'),
        ),
        migrations.AddField(
            model_name='ue',
            name='equivalente_a',
            field=models.ManyToManyField(blank=True, to='myFindings.ue'),
        ),
        migrations.AddField(
            model_name='ue',
            name='igual_a',
            field=models.ManyToManyField(blank=True, to='myFindings.ue'),
        ),
        migrations.AddField(
            model_name='ue',
            name='sobre',
            field=models.ManyToManyField(blank=True, to='myFindings.ue'),
        ),
    ]
