# Generated by Django 4.0.3 on 2022-03-14 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myFindings', '0003_rename_punto_cero_excavacion_altura_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inclusion',
            name='frecuencia',
            field=models.CharField(choices=[('Ausencia', 'Ausencia'), ('Ocasional', 'Ocasional'), ('Medio', 'Medio'), ('Frecuente', 'Frecuente')], max_length=10),
        ),
        migrations.AlterField(
            model_name='inclusion',
            name='grosor',
            field=models.CharField(choices=[('< 2 cm', '< 2 cm'), ('2-6 cm', '2-6 cm'), ('6-12 cm', '6-12 cm'), ('> 12 cm', '> 12 cm')], max_length=10),
        ),
        migrations.AlterField(
            model_name='inclusion',
            name='tipo',
            field=models.CharField(choices=[('Cenizas', 'Cenizas'), ('Carbones', 'Carbones'), ('Huesos', 'Huesos'), ('Adobe', 'Adobe'), ('Cañizo', 'Cañizo'), ('Tejas', 'Tejas'), ('Bloques', 'Bloques'), ('Cal', 'Cal'), ('Mortero', 'Mortero'), ('Enlucido', 'Enlucido')], max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='materialconstruida',
            name='nombre',
            field=models.CharField(choices=[('Piedra', 'Piedra'), ('Tierra cruda', 'Tierra cruda'), ('Cal', 'Cal'), ('Tierra cocida', 'Tierra cocida'), ('Madera', 'Madera')], max_length=15, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='materialsedimentaria',
            name='nombre',
            field=models.CharField(choices=[('Muestras', 'Muestras'), ('Metal', 'Metal'), ('Piedra', 'Piedra'), ('Arcilla', 'Arcilla'), ('Material construido', 'Material construido'), ('Cerámica', 'Cerámica'), ('Vidrio', 'Vidrio'), ('Fauna', 'Fauna'), ('Otros', 'Otros')], max_length=20, primary_key=True, serialize=False),
        ),
    ]
