# Generated by Django 4.0.4 on 2022-05-11 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myFindings', '0003_alter_ue_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='builtue',
            name='tipo',
            field=models.CharField(choices=[('Positiva', 'Positiva'), ('Negativa', 'Negativa')], default='Positiva', max_length=8),
        ),
    ]
