# Generated by Django 4.0.4 on 2022-05-12 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myFindings', '0003_alter_builtmaterial_options_alter_builtue_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fact',
            options={'verbose_name': 'hecho', 'verbose_name_plural': 'hechos'},
        ),
    ]
