# Generated by Django 4.0.4 on 2022-05-12 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myFindings', '0004_alter_fact_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ue',
            name='codigo',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AddConstraint(
            model_name='ue',
            constraint=models.UniqueConstraint(fields=('excavacion', 'n_orden'), name='ue_constraint'),
        ),
    ]
