# Generated by Django 4.0.4 on 2022-05-27 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myFindings', '0004_ue_bajo_ue_equivalente_a_ue_igual_a_ue_sobre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excavation',
            name='nombre',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre de la excavación'),
        ),
    ]
