# Generated by Django 4.0.4 on 2022-05-11 21:45

from django.db import migrations, models
import myFindings.models


class Migration(migrations.Migration):

    dependencies = [
        ('myFindings', '0004_alter_builtue_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excavation',
            name='n_excavacion',
            field=models.CharField(help_text='Ej. 1, 2, 3, etc', max_length=3, unique=True, validators=[myFindings.models.validate_excavation], verbose_name='Número de excavación'),
        ),
    ]
