# Generated by Django 4.0.3 on 2022-03-14 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myFindings', '0004_alter_inclusion_frecuencia_alter_inclusion_grosor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estancia',
            name='fase',
            field=models.CharField(choices=[('A: época contemporánea', (('A1', 'A1: 1800/1900'), ('A2', 'A2: 1900/2000'), ('A3', 'A3: época actual'))), ('B: época moderna', (('B1', 'B1: fase morisca'), ('B2', 'B2: fase cristiana'))), ('C: época medieval', (('C1', 'C1: fase emiral'), ('C2', 'C2: fase califal'), ('C3', 'C3: fase taifas'), ('C4', 'C4: fase almorávide/almohade'), ('C5', 'C5: fase nazarí'))), ('D: época romana', (('D1', 'D1: época republicana'), ('D2', 'D2: Alto Imperio'), ('D3', 'D3: Bajo Imperio'), ('D4', 'D4: Antigüedad tardía'))), ('E: época ibérica', (('E1', 'E1: Protoibérico'), ('E2', 'E2: Ibérico antiguo'), ('E3', 'E3: Ibérico pleno'), ('E4', 'E4: Ibérico tardío o final'))), ('F: Edad del Bronce', (('F1', 'F1: Bronce Final'), ('F2', 'F2: Bronce argárico'), ('F3', 'F3: Bronce antiguo')))], max_length=2),
        ),
        migrations.AlterField(
            model_name='fotografia',
            name='fase',
            field=models.CharField(choices=[('A: época contemporánea', (('A1', 'A1: 1800/1900'), ('A2', 'A2: 1900/2000'), ('A3', 'A3: época actual'))), ('B: época moderna', (('B1', 'B1: fase morisca'), ('B2', 'B2: fase cristiana'))), ('C: época medieval', (('C1', 'C1: fase emiral'), ('C2', 'C2: fase califal'), ('C3', 'C3: fase taifas'), ('C4', 'C4: fase almorávide/almohade'), ('C5', 'C5: fase nazarí'))), ('D: época romana', (('D1', 'D1: época republicana'), ('D2', 'D2: Alto Imperio'), ('D3', 'D3: Bajo Imperio'), ('D4', 'D4: Antigüedad tardía'))), ('E: época ibérica', (('E1', 'E1: Protoibérico'), ('E2', 'E2: Ibérico antiguo'), ('E3', 'E3: Ibérico pleno'), ('E4', 'E4: Ibérico tardío o final'))), ('F: Edad del Bronce', (('F1', 'F1: Bronce Final'), ('F2', 'F2: Bronce argárico'), ('F3', 'F3: Bronce antiguo')))], max_length=2),
        ),
        migrations.AlterField(
            model_name='hecho',
            name='fase',
            field=models.CharField(choices=[('A: época contemporánea', (('A1', 'A1: 1800/1900'), ('A2', 'A2: 1900/2000'), ('A3', 'A3: época actual'))), ('B: época moderna', (('B1', 'B1: fase morisca'), ('B2', 'B2: fase cristiana'))), ('C: época medieval', (('C1', 'C1: fase emiral'), ('C2', 'C2: fase califal'), ('C3', 'C3: fase taifas'), ('C4', 'C4: fase almorávide/almohade'), ('C5', 'C5: fase nazarí'))), ('D: época romana', (('D1', 'D1: época republicana'), ('D2', 'D2: Alto Imperio'), ('D3', 'D3: Bajo Imperio'), ('D4', 'D4: Antigüedad tardía'))), ('E: época ibérica', (('E1', 'E1: Protoibérico'), ('E2', 'E2: Ibérico antiguo'), ('E3', 'E3: Ibérico pleno'), ('E4', 'E4: Ibérico tardío o final'))), ('F: Edad del Bronce', (('F1', 'F1: Bronce Final'), ('F2', 'F2: Bronce argárico'), ('F3', 'F3: Bronce antiguo')))], max_length=2),
        ),
        migrations.AlterField(
            model_name='ue',
            name='fase',
            field=models.CharField(choices=[('A: época contemporánea', (('A1', 'A1: 1800/1900'), ('A2', 'A2: 1900/2000'), ('A3', 'A3: época actual'))), ('B: época moderna', (('B1', 'B1: fase morisca'), ('B2', 'B2: fase cristiana'))), ('C: época medieval', (('C1', 'C1: fase emiral'), ('C2', 'C2: fase califal'), ('C3', 'C3: fase taifas'), ('C4', 'C4: fase almorávide/almohade'), ('C5', 'C5: fase nazarí'))), ('D: época romana', (('D1', 'D1: época republicana'), ('D2', 'D2: Alto Imperio'), ('D3', 'D3: Bajo Imperio'), ('D4', 'D4: Antigüedad tardía'))), ('E: época ibérica', (('E1', 'E1: Protoibérico'), ('E2', 'E2: Ibérico antiguo'), ('E3', 'E3: Ibérico pleno'), ('E4', 'E4: Ibérico tardío o final'))), ('F: Edad del Bronce', (('F1', 'F1: Bronce Final'), ('F2', 'F2: Bronce argárico'), ('F3', 'F3: Bronce antiguo')))], max_length=2),
        ),
        migrations.AlterField(
            model_name='uesedimentaria',
            name='tipo_estructura',
            field=models.CharField(choices=[('Compacta', 'Compacta'), ('Suelta', 'Suelta'), ('Homogénea', 'Homogénea'), ('Heterogénea', 'Heterogénea')], max_length=15),
        ),
        migrations.AlterField(
            model_name='uesedimentaria',
            name='tipo_textura',
            field=models.CharField(choices=[('Arcilla', 'Arcilla'), ('Limo', 'Limo'), ('Arena', 'Arena'), ('Grava', 'Grava'), ('Cantos', 'Cantos'), ('Bloques', 'Bloques'), ('Cerámica', 'Cerámica'), ('Mortero', 'Mortero')], max_length=10),
        ),
    ]
