# Generated by Django 4.0.3 on 2022-03-14 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myFindings', '0005_alter_estancia_fase_alter_fotografia_fase_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ueconstruida',
            name='materialesconstruida',
            field=models.ManyToManyField(to='myFindings.materialconstruida'),
        ),
        migrations.AddField(
            model_name='uesedimentaria',
            name='materialessedimentaria',
            field=models.ManyToManyField(to='myFindings.materialsedimentaria'),
        ),
    ]
