# Generated by Django 4.0.4 on 2022-05-11 22:03

from django.db import migrations, models
import myFindings.models


class Migration(migrations.Migration):

    dependencies = [
        ('myFindings', '0005_alter_excavation_n_excavacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='n_estancia',
            field=models.CharField(help_text='Ej. 1, 2, 3, etc', max_length=3, unique=True, validators=[myFindings.models.validate_room], verbose_name='Número de estancia'),
        ),
        migrations.AlterField(
            model_name='ue',
            name='n_orden',
            field=models.CharField(help_text='Ej. 1, 2, 3, etc', max_length=3, validators=[myFindings.models.validate_ue], verbose_name='Número de orden'),
        ),
    ]
