# Generated by Django 4.0.3 on 2022-03-14 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myFindings', '0006_ueconstruida_materialesconstruida_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ueconstruida',
            old_name='materialesconstruida',
            new_name='materiales_construidos',
        ),
        migrations.RenameField(
            model_name='uesedimentaria',
            old_name='materialessedimentaria',
            new_name='materiales_sedimentarios',
        ),
    ]
