# Generated by Django 4.0.3 on 2022-03-14 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myFindings', '0007_rename_materialesconstruida_ueconstruida_materiales_construidos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ue',
            name='hecho',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='myFindings.hecho'),
        ),
    ]
