# Generated by Django 4.0.3 on 2022-03-14 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myFindings', '0008_alter_ue_hecho'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ue',
            name='hecho',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myFindings.hecho'),
        ),
    ]
