# Generated by Django 4.0.3 on 2022-03-16 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myFindings', '0009_alter_ue_hecho'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Inclusion',
        ),
    ]
