# Generated by Django 4.0.3 on 2022-03-16 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myFindings', '0010_delete_inclusion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inclusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Cenizas', 'Cenizas'), ('Carbones', 'Carbones'), ('Huesos', 'Huesos'), ('Adobe', 'Adobe'), ('Cañizo', 'Cañizo'), ('Tejas', 'Tejas'), ('Bloques', 'Bloques'), ('Cal', 'Cal'), ('Mortero', 'Mortero'), ('Enlucido', 'Enlucido')], max_length=10)),
                ('frecuencia', models.CharField(choices=[('Ausencia', 'Ausencia'), ('Ocasional', 'Ocasional'), ('Medio', 'Medio'), ('Frecuente', 'Frecuente')], max_length=10)),
                ('grosor', models.CharField(choices=[('< 2 cm', '< 2 cm'), ('2-6 cm', '2-6 cm'), ('6-12 cm', '6-12 cm'), ('> 12 cm', '> 12 cm')], max_length=10)),
                ('uesedimentaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myFindings.uesedimentaria')),
            ],
        ),
    ]
