# Generated by Django 4.0.3 on 2022-03-16 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myFindings', '0011_inclusion'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='inclusion',
            unique_together={('tipo', 'uesedimentaria')},
        ),
    ]
