# Generated by Django 4.0.3 on 2022-03-16 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myFindings', '0012_alter_inclusion_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='excavacion',
            old_name='coordenada_x',
            new_name='latitud',
        ),
        migrations.RenameField(
            model_name='excavacion',
            old_name='coordenada_y',
            new_name='longitud',
        ),
        migrations.RenameField(
            model_name='ue',
            old_name='coordenada_x',
            new_name='latitud',
        ),
        migrations.RenameField(
            model_name='ue',
            old_name='coordenada_y',
            new_name='longitud',
        ),
        migrations.AddField(
            model_name='ue',
            name='codigo',
            field=models.CharField(default='000000', max_length=6, unique=True),
        ),
    ]
