# Generated by Django 4.0.3 on 2022-03-16 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myFindings', '0013_rename_coordenada_x_excavacion_latitud_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ueconstruida',
            name='n_estructura',
            field=models.IntegerField(default=0),
        ),
    ]
