# Generated by Django 4.0.3 on 2022-03-17 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myFindings', '0014_ueconstruida_n_estructura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estancia',
            name='n_estancia',
            field=models.CharField(max_length=5, unique=True),
        ),
    ]
