# Generated by Django 4.0.3 on 2022-03-17 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myFindings', '0015_alter_estancia_n_estancia'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='hecho',
            unique_together={('letra', 'numero')},
        ),
    ]
