# Generated by Django 4.0.3 on 2022-03-17 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myFindings', '0016_alter_hecho_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='hecho',
            unique_together=set(),
        ),
    ]
