# Generated by Django 4.0.3 on 2022-03-17 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myFindings', '0017_alter_hecho_unique_together'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='hecho',
            constraint=models.UniqueConstraint(fields=('letra', 'numero'), name='fact_constraint'),
        ),
    ]
