# Generated by Django 4.0.3 on 2022-03-17 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myFindings', '0018_hecho_fact_constraint'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='inclusion',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='inclusion',
            constraint=models.UniqueConstraint(fields=('tipo', 'uesedimentaria'), name='inclusion_constraint'),
        ),
    ]
