# Generated by Django 4.0.3 on 2022-03-31 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myFindings', '0020_alter_estancia_elevacion_alter_estancia_n_planta_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ueconstruida',
            name='materiales_construidos',
        ),
        migrations.RemoveField(
            model_name='uesedimentaria',
            name='materiales_sedimentarios',
        ),
        migrations.AddField(
            model_name='ueconstruida',
            name='materiales',
            field=models.ManyToManyField(blank=True, to='myFindings.materialconstruida'),
        ),
        migrations.AddField(
            model_name='uesedimentaria',
            name='materiales',
            field=models.ManyToManyField(blank=True, to='myFindings.materialsedimentaria'),
        ),
        migrations.AlterField(
            model_name='estancia',
            name='autor',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='estancia',
            name='croquis_planta',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='estancia',
            name='elevacion',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='estancia',
            name='fase',
            field=models.CharField(blank=True, choices=[('A: época contemporánea', (('A1', 'A1: Siglo XVIII'), ('A2', 'A2: Siglo XIX'), ('A3', 'A3: Siglo XX'))), ('B: época moderna', (('B1', 'B1: Siglo XV'), ('B2', 'B2: Siglo XVI'), ('B3', 'B3: Siglo XVII'))), ('C: época medieval', (('C1', 'C1: fase emiral'), ('C2', 'C2: fase califal'), ('C3', 'C3: fase taifas'), ('C4', 'C4: fase almorávide/almohade'), ('C5', 'C5: fase nazarí'))), ('D: época romana', (('D1', 'D1: época republicana'), ('D2', 'D2: Alto Imperio'), ('D3', 'D3: Bajo Imperio'), ('D4', 'D4: Antigüedad tardía'))), ('E: época ibérica', (('E1', 'E1: Protoibérico-orientalizante'), ('E2', 'E2: Ibérico antiguo'), ('E3', 'E3: Ibérico pleno'), ('E4', 'E4: Ibérico tardío o final'))), ('F: Edad del Bronce', (('F1', 'F1: Bronce Antiguo'), ('F2', 'F2: Bronce Pleno'), ('F3', 'F3: Bronce Tardío'), ('F4', 'F4: Bronce Final')))], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='estancia',
            name='n_planta',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='estancia',
            name='n_seccion',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='estancia',
            name='n_sector',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='estancia',
            name='n_zona',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='estancia',
            name='observaciones',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='estancia',
            name='periodo',
            field=models.CharField(blank=True, choices=[('Siglo XVIII', 'Contemporánea: Siglo XVIII'), ('Siglo XIX', 'Contemporánea: Siglo XIX'), ('Siglo XX', 'Contemporánea: Siglo XX'), ('Siglo XV', 'Moderna: Siglo XV'), ('Siglo XVI', 'Moderna: Siglo XVI'), ('Siglo XVII', 'Moderna: Siglo XVII'), ('Fase emiral', 'Medieval: emiral'), ('Fase califal', 'Medieval: califal'), ('Fase taifas', 'Medieval: taifas'), ('Fase invasiones almorávides y almohades', 'Medieval: almorávide/almohade'), ('Fase nazarí', 'Medieval: nazarí'), ('Fase republicana', 'Romana: época republicana'), ('Fase Altoimperial', 'Romana: Alto Imperio'), ('Fase Bajoimperial', 'Romana: Bajo Imperio'), ('Antigüedad tardía', 'Romana: Antigüedad tardía'), ('Protoibérico-orientalizante', 'Ibérica: Protoibérico'), ('Ibérico antiguo', 'Ibérica: Ibérico antiguo'), ('Ibérico pleno', 'Ibérica: Ibérico pleno'), ('Ibérico final', 'Ibérica: Ibérico tardío o final'), ('Bronce antiguo', 'Edad del Bronce: Antiguo'), ('Bronce pleno', 'Edad del Bronce: Pleno'), ('Bronce tardío', 'Edad del Bronce: Tardío'), ('Bronce final', 'Edad del Bronce: Final')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='estancia',
            name='taq',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='estancia',
            name='tpq',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='excavacion',
            name='altura',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='excavacion',
            name='latitud',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='excavacion',
            name='longitud',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fotografia',
            name='descripcion',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='fotografia',
            name='dist_focal',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fotografia',
            name='estancia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myFindings.estancia'),
        ),
        migrations.AlterField(
            model_name='fotografia',
            name='fase',
            field=models.CharField(blank=True, choices=[('A: época contemporánea', (('A1', 'A1: Siglo XVIII'), ('A2', 'A2: Siglo XIX'), ('A3', 'A3: Siglo XX'))), ('B: época moderna', (('B1', 'B1: Siglo XV'), ('B2', 'B2: Siglo XVI'), ('B3', 'B3: Siglo XVII'))), ('C: época medieval', (('C1', 'C1: fase emiral'), ('C2', 'C2: fase califal'), ('C3', 'C3: fase taifas'), ('C4', 'C4: fase almorávide/almohade'), ('C5', 'C5: fase nazarí'))), ('D: época romana', (('D1', 'D1: época republicana'), ('D2', 'D2: Alto Imperio'), ('D3', 'D3: Bajo Imperio'), ('D4', 'D4: Antigüedad tardía'))), ('E: época ibérica', (('E1', 'E1: Protoibérico-orientalizante'), ('E2', 'E2: Ibérico antiguo'), ('E3', 'E3: Ibérico pleno'), ('E4', 'E4: Ibérico tardío o final'))), ('F: Edad del Bronce', (('F1', 'F1: Bronce Antiguo'), ('F2', 'F2: Bronce Pleno'), ('F3', 'F3: Bronce Tardío'), ('F4', 'F4: Bronce Final')))], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='fotografia',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='fotografia',
            name='tipo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='fotografia',
            name='ue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myFindings.ue'),
        ),
        migrations.AlterField(
            model_name='fotografia',
            name='vista_desde',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='hecho',
            name='año',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hecho',
            name='comentarios',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='hecho',
            name='croquis_plan',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='hecho',
            name='croquis_seccion',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='hecho',
            name='definicion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='hecho',
            name='estancia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myFindings.estancia'),
        ),
        migrations.AlterField(
            model_name='hecho',
            name='estructura',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hecho',
            name='fase',
            field=models.CharField(blank=True, choices=[('A: época contemporánea', (('A1', 'A1: Siglo XVIII'), ('A2', 'A2: Siglo XIX'), ('A3', 'A3: Siglo XX'))), ('B: época moderna', (('B1', 'B1: Siglo XV'), ('B2', 'B2: Siglo XVI'), ('B3', 'B3: Siglo XVII'))), ('C: época medieval', (('C1', 'C1: fase emiral'), ('C2', 'C2: fase califal'), ('C3', 'C3: fase taifas'), ('C4', 'C4: fase almorávide/almohade'), ('C5', 'C5: fase nazarí'))), ('D: época romana', (('D1', 'D1: época republicana'), ('D2', 'D2: Alto Imperio'), ('D3', 'D3: Bajo Imperio'), ('D4', 'D4: Antigüedad tardía'))), ('E: época ibérica', (('E1', 'E1: Protoibérico-orientalizante'), ('E2', 'E2: Ibérico antiguo'), ('E3', 'E3: Ibérico pleno'), ('E4', 'E4: Ibérico tardío o final'))), ('F: Edad del Bronce', (('F1', 'F1: Bronce Antiguo'), ('F2', 'F2: Bronce Pleno'), ('F3', 'F3: Bronce Tardío'), ('F4', 'F4: Bronce Final')))], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='hecho',
            name='sector',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hecho',
            name='taq',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hecho',
            name='tpq',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hecho',
            name='zona',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inclusion',
            name='frecuencia',
            field=models.CharField(blank=True, choices=[('Ausencia', 'Ausencia'), ('Ocasional', 'Ocasional'), ('Medio', 'Medio'), ('Frecuente', 'Frecuente')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='inclusion',
            name='grosor',
            field=models.CharField(blank=True, choices=[('< 2 cm', '< 2 cm'), ('2-6 cm', '2-6 cm'), ('6-12 cm', '6-12 cm'), ('> 12 cm', '> 12 cm')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='materialsedimentaria',
            name='nombre',
            field=models.CharField(choices=[('Muestras', 'Muestras'), ('Metal', 'Metal'), ('Piedra', 'Piedra'), ('Arcilla', 'Arcilla'), ('Material construido', 'Material construido'), ('Cerámica', 'Cerámica'), ('Vidrio', 'Vidrio'), ('Fauna', 'Fauna'), ('Otros', 'Otros')], max_length=21, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ue',
            name='autor',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='ue',
            name='año',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ue',
            name='cota_inferior_diff',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ue',
            name='cota_superior_diff',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ue',
            name='croquis_planta',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='ue',
            name='croquis_seccion',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='ue',
            name='descripcion',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ue',
            name='elevacion_n',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ue',
            name='excavacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myFindings.excavacion', to_field='n_excavacion'),
        ),
        migrations.AlterField(
            model_name='ue',
            name='fase',
            field=models.CharField(blank=True, choices=[('A: época contemporánea', (('A1', 'A1: Siglo XVIII'), ('A2', 'A2: Siglo XIX'), ('A3', 'A3: Siglo XX'))), ('B: época moderna', (('B1', 'B1: Siglo XV'), ('B2', 'B2: Siglo XVI'), ('B3', 'B3: Siglo XVII'))), ('C: época medieval', (('C1', 'C1: fase emiral'), ('C2', 'C2: fase califal'), ('C3', 'C3: fase taifas'), ('C4', 'C4: fase almorávide/almohade'), ('C5', 'C5: fase nazarí'))), ('D: época romana', (('D1', 'D1: época republicana'), ('D2', 'D2: Alto Imperio'), ('D3', 'D3: Bajo Imperio'), ('D4', 'D4: Antigüedad tardía'))), ('E: época ibérica', (('E1', 'E1: Protoibérico-orientalizante'), ('E2', 'E2: Ibérico antiguo'), ('E3', 'E3: Ibérico pleno'), ('E4', 'E4: Ibérico tardío o final'))), ('F: Edad del Bronce', (('F1', 'F1: Bronce Antiguo'), ('F2', 'F2: Bronce Pleno'), ('F3', 'F3: Bronce Tardío'), ('F4', 'F4: Bronce Final')))], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='ue',
            name='interpretacion',
            field=models.CharField(blank=True, choices=[('Ocupación', 'Ocupación'), ('Abandono', 'Abandono'), ('Contrucción', 'Construcción'), ('Paleosuelo', 'Paleosuelo'), ('Reinstalación', 'Reinstalación'), ('Coluvión/Aluvión', 'Coluvión/Aluvión'), ('Destrucción', 'Destrucción'), ('Relleno', 'Relleno'), ('Otras', 'Otras')], max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='ue',
            name='latitud',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ue',
            name='longitud',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ue',
            name='observaciones',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ue',
            name='pendiente_inferior',
            field=models.CharField(blank=True, choices=[('Norte', 'Norte'), ('Sur', 'Sur'), ('Este', 'Este'), ('Oeste', 'Oeste'), ('Noroeste', 'Noroeste'), ('Noreste', 'Noreste'), ('Suroeste', 'Suroeste'), ('Sureste', 'Sureste')], max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='ue',
            name='pendiente_superior',
            field=models.CharField(blank=True, choices=[('Norte', 'Norte'), ('Sur', 'Sur'), ('Este', 'Este'), ('Oeste', 'Oeste'), ('Noroeste', 'Noroeste'), ('Noreste', 'Noreste'), ('Suroeste', 'Suroeste'), ('Sureste', 'Sureste')], max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='ue',
            name='periodo',
            field=models.CharField(blank=True, choices=[('Siglo XVIII', 'Contemporánea: Siglo XVIII'), ('Siglo XIX', 'Contemporánea: Siglo XIX'), ('Siglo XX', 'Contemporánea: Siglo XX'), ('Siglo XV', 'Moderna: Siglo XV'), ('Siglo XVI', 'Moderna: Siglo XVI'), ('Siglo XVII', 'Moderna: Siglo XVII'), ('Fase emiral', 'Medieval: emiral'), ('Fase califal', 'Medieval: califal'), ('Fase taifas', 'Medieval: taifas'), ('Fase invasiones almorávides y almohades', 'Medieval: almorávide/almohade'), ('Fase nazarí', 'Medieval: nazarí'), ('Fase republicana', 'Romana: época republicana'), ('Fase Altoimperial', 'Romana: Alto Imperio'), ('Fase Bajoimperial', 'Romana: Bajo Imperio'), ('Antigüedad tardía', 'Romana: Antigüedad tardía'), ('Protoibérico-orientalizante', 'Ibérica: Protoibérico'), ('Ibérico antiguo', 'Ibérica: Ibérico antiguo'), ('Ibérico pleno', 'Ibérica: Ibérico pleno'), ('Ibérico final', 'Ibérica: Ibérico tardío o final'), ('Bronce antiguo', 'Edad del Bronce: Antiguo'), ('Bronce pleno', 'Edad del Bronce: Pleno'), ('Bronce tardío', 'Edad del Bronce: Tardío'), ('Bronce final', 'Edad del Bronce: Final')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ue',
            name='plano_n',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ue',
            name='seccion_n',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ue',
            name='sector',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ue',
            name='taq',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ue',
            name='tpq',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ueconstruida',
            name='n_estructura',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ueconstruida',
            name='sistema_constructivo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ueconstruida',
            name='tipo',
            field=models.CharField(blank=True, choices=[('Positiva', 'Positiva'), ('Negativa', 'Negativa')], max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='uesedimentaria',
            name='tipo_estructura',
            field=models.CharField(blank=True, choices=[('Compacta', 'Compacta'), ('Suelta', 'Suelta'), ('Homogénea', 'Homogénea'), ('Heterogénea', 'Heterogénea')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='uesedimentaria',
            name='tipo_textura',
            field=models.CharField(blank=True, choices=[('Arcilla', 'Arcilla'), ('Limo', 'Limo'), ('Arena', 'Arena'), ('Grava', 'Grava'), ('Cantos', 'Cantos'), ('Bloques', 'Bloques'), ('Cerámica', 'Cerámica'), ('Mortero', 'Mortero')], max_length=10, null=True),
        ),
    ]
