# Generated by Django 4.0.3 on 2022-04-09 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myFindings', '0021_remove_ueconstruida_materiales_construidos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialconstruida',
            name='nombre',
            field=models.CharField(max_length=40, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='materialsedimentaria',
            name='nombre',
            field=models.CharField(max_length=40, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ue',
            name='interpretacion',
            field=models.CharField(blank=True, choices=[('Ocupación', 'Ocupación'), ('Abandono', 'Abandono'), ('Construcción', 'Construcción'), ('Paleosuelo', 'Paleosuelo'), ('Reinstalación', 'Reinstalación'), ('Coluvión/Aluvión', 'Coluvión/Aluvión'), ('Destrucción', 'Destrucción'), ('Relleno', 'Relleno'), ('Otras', 'Otras')], max_length=16, null=True),
        ),
    ]
