# Generated by Django 4.0.3 on 2022-04-09 23:12

from django.db import migrations

def initialize_built_materials(apps, schema_editor):
    MaterialConstruida = apps.get_model('myFindings', 'MaterialConstruida')
    MaterialConstruida.objects.create(nombre='Piedra')
    MaterialConstruida.objects.create(nombre='Tierra cruda')
    MaterialConstruida.objects.create(nombre='Cal')
    MaterialConstruida.objects.create(nombre='Tierra cocida')
    MaterialConstruida.objects.create(nombre='Madera')
    MaterialConstruida.objects.create(nombre='Otros')
    
def initialize_sedimentary_materials(apps, schema_editor):
    MaterialSedimentaria = apps.get_model('myFindings', 'MaterialSedimentaria')
    MaterialSedimentaria.objects.create(nombre='Muestras')
    MaterialSedimentaria.objects.create(nombre='Metal')
    MaterialSedimentaria.objects.create(nombre='Piedra')
    MaterialSedimentaria.objects.create(nombre='Arcilla')
    MaterialSedimentaria.objects.create(nombre='Material construcción')
    MaterialSedimentaria.objects.create(nombre='Cerámica')
    MaterialSedimentaria.objects.create(nombre='Vidrio')
    MaterialSedimentaria.objects.create(nombre='Fauna')
    MaterialSedimentaria.objects.create(nombre='Otros')

class Migration(migrations.Migration):

    dependencies = [
        ('myFindings', '0022_alter_materialconstruida_nombre_and_more'),
    ]

    operations = [
        migrations.RunPython(initialize_built_materials),
        migrations.RunPython(initialize_sedimentary_materials),
    ]
