# Generated by Django 4.0.4 on 2022-04-24 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myFindings', '0023_auto_20220409_2312'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MaterialConstruida',
            new_name='BuiltMaterial',
        ),
        migrations.RenameModel(
            old_name='UEConstruida',
            new_name='BuiltUE',
        ),
        migrations.RenameModel(
            old_name='Excavacion',
            new_name='Excavation',
        ),
        migrations.RenameModel(
            old_name='Hecho',
            new_name='Fact',
        ),
        migrations.RenameModel(
            old_name='Fotografia',
            new_name='Photo',
        ),
        migrations.RenameModel(
            old_name='Estancia',
            new_name='Room',
        ),
        migrations.RenameModel(
            old_name='MaterialSedimentaria',
            new_name='SedimentaryMaterial',
        ),
        migrations.RenameModel(
            old_name='UESedimentaria',
            new_name='SedimentaryUE',
        ),
    ]
