name: Build images
on:
  push:
    paths:
      - '.github/workflows/build.yml'
      - 'code/*'

jobs:
  build-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Build images
        run: |
          cd code/ && touch .env
          docker-compose build
