name: Build LaTeX documentation
on:
  push:
    branches: [ main, development ]
  pull_request:
    branches: [ main, development ]
jobs:
  build-latex:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          working_directory: doc/
          root_file: proyecto.tex
          latexmk_shell_escape: true
